# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Learning to Program in Swift
email: jeffblagdon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Don't you want to do this?
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/jefflovejapan/learningswift" # the base hostname & protocol for your site
twitter_username: blagdon
github_username:  jefflovejapan

# Build settings
markdown: kramdown
